### ISSUE TITLE
Task 17: FrontEnd Multimedia (US6)

### ISSUE THREAD

**Issue by eugeniblas** [UB-ES-2018/buzzer#34]

**Comment by sergioBarril** [comment]
Ayer estuve 2h y media mirando cómo reproducir los archivos multimedia y pensando cómo me convenía que me llegaran desde el Backend. Además, empecé a mirarme el tema de alertas, para poder avisar cuando hay algún error.

Hoy he estado 3h y media integrando la faena de backend con la de frontend, corregiendo pequeños bugs y comprobando que todo funcione. 

También le he añadido estilo (de tamaño solo, de momento, para que no se salgan las imágenes del contenedor), así como un script para que se amplíen las imágenes al hacerles clic.

Queda pendiente implementar las alertas

**Comment by sergioBarril** [comment]
Hoy he estado 1h y media haciendo las alertas, y media hora haciendo los merge para subirlo a sprint.

De momento la doy por acabada.

**Comment by eugeniblas** [comment]
OK merge
