### ISSUE TITLE
Task 19: Profile Buzz (US7)

### ISSUE THREAD

**Issue by eugeniblas** [UB-ES-2018/buzzer#36]

**Comment by Mccornudella** [comment]
Shan dedicat 2 hores a la recerca d'informacio dels formularis i la comunicació

**Comment by Mccornudella** [comment]
S'han dedicat unes altres dues hores a construir el form en la seva funcio amb totes les fields.
Tambe integrar amb un modal per a poder editar i fer una mica de backend per tal de poder fer-ho funcinal

**Comment by eugeniblas** [comment]
Code review realizado. Se ha comprobado que se puede editar el profile y sale correctamente los buzzers del usuario.
