### ISSUE TITLE
Task 21: BackEnd Hashtag (US8)

### ISSUE THREAD

**Issue by eugeniblas** [UB-ES-2018/buzzer#38]

**Comment by Soulk97** [comment]
14/11 0,5h
Code review US8

**Comment by eugeniblas** [comment]
4h (model 1h + backend 3h)
08/11  1h
09/11  1h
10/11  1h
11/11  1h

**Comment by eugeniblas** [comment]
Code Review realizado. Los hashtags funcionan correctamente. Merge en SP3 realizado.
