### ISSUE TITLE
Task 5: Base de Datos para Users

### ISSUE THREAD

**Issue by sergioBarril** [UB-ES-2018/buzzer#7]
Hacer la base de datos para guardar los Users.

**Comment by eugeniblas** [comment]
-Ja he provat la base de dades de usuaris:  auth.User  i extesa a Buser (README_BD)
-He pujat els canvis a T5-BD_USERS i fet merge a SP-1 (despres de comprovar que no hi ha conflictes)

**Comment by Soulk97** [comment]
### **Code Review:**

La base de datos funciona bien, guarda los usuarios y se puede acceder a ellos.
Al entrar a` buzzer/users` debería salir algo, pero da un error de  `RelatedObjectDoesNotExist.`

Al entrar al usuario en específico funciona bien.

Los username yo los guardaría sin @, no veo sentido a ponérselo a todos dentro de la base de datos, @ funciona para referenciar a un usuario en un mensaje, que le llegue la notificación y poder entrar a su perfil

Personalmente añadiría una clase Profile linkeada a Buser donde guardar campos como location o url, en vez de ponerlos todos en Buser, para tenerlo todo más ordenado, pero funcionalmente no tendría diferencia.
En su momento no nos dimos cuenta de la necesidad de poner el máximo de longitud de cada campo que tiene twitter, estaría bien revisarlo y ponerlo.

La base de datos funciona y no debería dar errores al hacer un merge.
